# Generated by Django 4.2.13 on 2026-05-25 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breeding_date', models.DateField()),
                ('method', models.CharField(choices=[('Natural', 'Natural'), ('AI', 'Artificial Insemination')], max_length=10)),
                ('semen_batch', models.CharField(blank=True, max_length=100)),
                ('expected_calving', models.DateField(blank=True, null=True)),
                ('actual_calving', models.DateField(blank=True, null=True)),
                ('calving_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Stillbirth', 'Stillbirth')], max_length=15, null=True)),
                ('calf_tag_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'breeding_records',
                'ordering': ['-breeding_date'],
            },
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('breed', models.CharField(choices=[('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Gir', 'Gir'), ('Sahiwal', 'Sahiwal'), ('Murrah', 'Murrah (Buffalo)'), ('Crossbreed', 'Crossbreed'), ('Other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Lactating', 'Lactating'), ('Dry', 'Dry'), ('Pregnant', 'Pregnant'), ('Sold', 'Sold'), ('Deceased', 'Deceased')], default='Active', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cattle',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('Routine', 'Routine Checkup'), ('Illness', 'Illness'), ('Injury', 'Injury'), ('Calving', 'Calving'), ('Deworming', 'Deworming')], max_length=20)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medicines_given', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'health_records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('administered_on', models.DateField()),
                ('next_due_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cattle.cattle')),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['next_due_date'],
            },
        ),
    ]
