# Generated by Django 4.2.13 on 2026-05-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle.cattle'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cattle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='bull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired', to='cattle.cattle'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='cattle.cattle'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['next_due_date'], name='vaccination_next_du_94e369_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['status'], name='idx_cattle_status_active'),
        ),
    ]
