# Generated by Django 4.2.13 on 2026-05-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Feed', 'Feed & Fodder'), ('Medicine', 'Medicine & Supplements'), ('Equipment', 'Equipment'), ('Packaging', 'Packaging'), ('Chemicals', 'Chemicals & Disinfectants'), ('Other', 'Other')], max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('litre', 'Litre'), ('unit', 'Unit'), ('box', 'Box'), ('bag', 'Bag'), ('bottle', 'Bottle')], max_length=10)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Consumption', 'Consumption'), ('Adjustment', 'Adjustment'), ('Return', 'Return'), ('Wastage', 'Wastage')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('txn_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
