# Generated by Django 4.2.13 on 2026-05-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Draft', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer')),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'db_table': 'order_lines',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hsn_code', models.CharField(default='0402', max_length=4)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Paid', 'Paid'), ('PartiallyPaid', 'Partially Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('otp_hash', models.TextField(blank=True)),
                ('otp_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Scheduled', max_length=15)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.salesorder')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
