# Generated by Django 4.2.13 on 2026-05-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_date', models.DateField()),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_yield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deviation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Open', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_alerts', to='cattle.cattle')),
            ],
            options={
                'db_table': 'yield_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('quantity_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('snf_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('Rejected', 'Rejected')], max_length=10, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_collections', to='cattle.cattle')),
                ('field_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milk_collections',
                'indexes': [models.Index(fields=['collection_date'], name='milk_collec_collect_b90413_idx'), models.Index(fields=['cattle'], name='milk_collec_cattle__20e117_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='milkcollection',
            constraint=models.UniqueConstraint(fields=('cattle', 'collection_date', 'shift'), name='uq_milk_collection'),
        ),
    ]
